production: false

database:
  credentials:
    connectionString: mongodb://localhost/corella-local
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    ignoreUndefined: false
    keepAlive: true

server:
  http:
    protocol: http
    address: 127.0.0.1
    host: localhost:8080
    port: 8080

  cors:
    allowedOrigins:
      - http://localhost:8000
    allowedHeaders:
      - origin
      - content-type
      - cookie


logger:
  # Recommended false for production
  pretty: true
  time: true
  # Recommended false for production
  isoTime: true
  level: debug # debug | info

user:
  registration: true

  session:
    maximum: 10

    cookie:
      path: /
      domain: localhost
      sameSite: strict
      maxAge: 5184000000

  superadmin:
    username: admin
    email: admin@nowhere.org
    password: SuperSecretPassword